# Generated by Django 5.2.1 on 2025-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
