# Generated by Django 5.2.1 on 2025-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('football_count', models.IntegerField(default=0)),
                ('show_addition', models.BooleanField(default=False)),
                ('first_group', models.IntegerField(blank=True, null=True)),
                ('second_group', models.IntegerField(blank=True, null=True)),
                ('options', models.JSONField()),
                ('correct_answer', models.IntegerField()),
                ('explanation', models.TextField()),
            ],
        ),
    ]
